# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: With high probability
email: sdavie2@uic.edu
description: > # this means to ignore newlines until "baseurl:"
  A place for math, computer science, and other things I find interesting
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samidavies.github.io" # the base hostname & protocol for your site
github_username:  samidavies

# Build settings
markdown: kramdown
